server:
  port: 9000
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://10.129.2.152;DatabaseName=FCSTASSESSMENT
    username: sa
    password: AMO2.255
mybatis:
   mapper-locations: classpath*:mapper/*.xml
   type-aliases-package: com.pingchuan.weather.entity
pagehelper:
  helper-dialect: sqlserver
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
